# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'
# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!

target 'DouYuTV' do

pod 'Alamofire', '~> 4.5.1'
pod 'Kingfisher'

end
